<!DOCTYPE html>
<html>
    <title>AlphaIPTV</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://github.hubspot.com/odometer/themes/odometer-theme-default.css" />
    <link rel="stylesheet" href="<?php echo CSS; ?>Count.css"/>
    <script src="http://github.hubspot.com/odometer/odometer.js"></script>

    <style>
        body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
        .w3-row-padding img {margin-bottom: 12px}
        /* Set the width of the sidebar to 120px */
        .w3-sidebar {width: 120px;background: #222;}
        /* Add a left margin to the "page content" that matches the width of the sidebar (120px) */
        #main {margin-left: 120px}
        /* Remove margins from "page content" on small screens */
        @media only screen and (max-width: 600px) {#main {margin-left: 0}}
    </style>
    <body class="w3-black">

        <!-- Icon Bar (Sidebar - hidden on small screens) -->
        <nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
            <!-- Avatar image in top left corner -->
            <img src="<?php echo IMG; ?>Sem.png" style="width:100%">
            <a href="#" class="w3-bar-item w3-button w3-padding-large w3-black">
                <i class="fa fa-home w3-xxlarge"></i>
                <p>Início</p>
            </a>
            <a href="Oque" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                <i class="fa fa-user w3-xxlarge"></i>
                <p>Sobre nós
                </p>
            </a>
            <a href="#photos" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                <i class="fa fa-eye w3-xxlarge"></i>
                <p>PHOTOS</p>
            </a>
            <a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                <i class="fa fa-envelope w3-xxlarge"></i>
                <p>CONTACT</p>
            </a>
        </nav>

        <!-- Navbar on small screens (Hidden on medium and large screens) -->
        <div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
            <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
                <a href="#" class="w3-bar-item w3-button" style="width:25% !important">Iníco</a>
                <a href="Oque" class="w3-bar-item w3-button" style="width:25% !important">Oque</a>
                <a href="#photos" class="w3-bar-item w3-button" style="width:25% !important">PHOTOS</a>
                <a href="#contact" class="w3-bar-item w3-button" style="width:25% !important">CONTACT</a>
            </div>
        </div>

        <!-- Page Content -->
        <div class="w3-padding-large" id="main">
            <!-- Header/Home -->
            <header class="w3-container w3-padding-32 w3-center w3-black" id="home">

                <h1 class="w3-jumbo"><span class="w3-hide-small"></span>AlphaIPTV  <a id="odometer" title="Numero de Clientes" class="odometer"></a></h1>
                <script type="text/javascript">
                    setTimeout(function () {
                        odometer.innerHTML = 622;
                    }, 1000);
                </script>
                <p><?php
                    $hr = date(" H ");
                    if ($hr >= 12 && $hr < 18) {
                        $resp = "Aqui você poderá tirar todas suas dúvidas e até mesmo conhecer mais um pouco sobre nós. Seja bem-vindo e tenha uma Boa tarde!";
                    } else if ($hr >= 18 && $hr < 22) {
                        $resp = "Aqui você poderá tirar todas suas dúvidas e até mesmo conhecer mais um pouco sobre nós. Seja bem-vindo e tenha uma Boa noite!";
                    } else if ($hr >= 0 && $hr < 12) {
                        $resp = "Aqui você poderá tirar todas suas dúvidas e até mesmo conhecer mais um pouco sobre nós. Seja bem-vindo e tenha um Bom dia!";
                    } else {
                        $resp = "Nosso horário de atendimento é das 8:00 até as 22:00 horas. "
                                . "Assistências, Links e Duvidas só serão atendidos durante esse horário de expediente.";
                    }
                    echo "$resp";
                    ?></p>
                <img src="<?php echo IMG; ?>images/logo-site.png" alt="boy" class="w3-image" style=" background-size: cover;" >
            </header>
        </div>

    </body>
</html>
