<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Leonardo Pereira">
        <meta name="generator" content="Alpha IPTV">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="<?php echo IMG; ?>icon.png" type="image/x-icon">
        <?php
        echo $add_css;
        echo $add_js;
        ?>
    </head>
    <body>
        <div class="container">